// Generated by https://pagedraw.io/pages/10640
import React from 'react';
import {TextField} from '@material-ui/core';
import {Switch} from '@material-ui/core';
import {Button} from '@material-ui/core';
import './mainpage.css';


function render() {
    return <div className="mainpage-mainpage-1">
        <div className="mainpage-0">
            <div className="mainpage-text-0">Hello world</div>
        </div>
        <div className="mainpage-1">
            <div className="mainpage-rectangle-7">
                <div className="mainpage-1-0-0">
                    <div className="mainpage-textfield_instance-9">
                        <TextField defaultValue={""} helperText={""} label={"Username"} disabled={false} error={false} fullWidth={true} /> 
                    </div>
                </div>
                <div className="mainpage-1-0-1">
                    <div className="mainpage-textfield_instance-2">
                        <TextField defaultValue={""} helperText={""} label={"Email"} disabled={false} error={false} fullWidth={true} /> 
                    </div>
                </div>
                <div className="mainpage-1-0-2">
                    <div className="mainpage-switch_instance-3">
                        <Switch color={"default"} checked={false} disabled={false} /> 
                    </div>
                    <div className="mainpage-1-0-2-1">
                        <div className="mainpage-1-0-2-1-0">
                            <div className="mainpage-button_instance-9">
                                <Button variant={"raised"} size={"medium"} color={"primary"} children={"Submit"} disabled={false} fullWidth={true} /> 
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div className="mainpage-2" /> 
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
